### ISSUE TITLE
Problem with Kriging using Gaussian Variogram

### ISSUE THREAD

**Issue by tianzeliu** [juliohm/GeoStats.jl#29]
I was testing Kriging my data with different variograms and found that Gaussian variogram seems to be constantly producing problems.  When I used Matern (and also other types such as Spherical) variograms the results I got looked normal (see MaternExample.png). However, when I used Gaussian variogram, the results looked awful with patches of very extreme values (see GaussianExample.png ). The specific variograms I used for the two examples are:
`γtheo = MaternVariogram(sill=1.35, range=175.0, nugget=0.15, distance=Haversine(6371))` 
`γtheo = GaussianVariogram(sill=1.2, range=300.0, nugget=0.15, distance=Haversine(6371))`
I am also attaching my dataset in (lon,lat,val) format. Thanks a lot!

![gaussianexample](https://user-images.githubusercontent.com/23426043/48689316-cea31100-eb7e-11e8-8850-a094daa7c3cb.png)
![maternexample](https://user-images.githubusercontent.com/23426043/48689317-cea31100-eb7e-11e8-9b82-dd80da208f38.png)
[StnRes_label.txt](https://github.com/juliohm/GeoStats.jl/files/2594004/StnRes_label.txt)

**Comment by juliohm** [comment]
@tianzeliu could you please provide a minimum example so that I can reproduce the exact same plot?

Thank you for reporting the issue again.

**Comment by juliohm** [comment]
I am happy to say that this longstanding issue is now solved. Thank you for reporting it again, otherwise I would have delayed the investigation further.

There was a very subtle bug in the theoretical variogram expressions where the discontinuity jump at the origin was not being applied. I fixed all the variogram models accordingly as shown here: https://github.com/juliohm/Variography.jl/commit/84b540c1dbfa478bc26826487efa7580d3af4329

I have tested with your data set again, and the solution looks correct now. As a general rule, when you find ill-conditioned systems in the future, the solution is to add a nugget effect as you did above. This is equivalent to adding a positive term to the diagonal of the covariance which improves the condition number.

The new release of Variography.jl should come out soon and you can get it by updating with the Julia package manager.

Marking as solved. :+1:
