### ISSUE TITLE
Solution postprocessing 

### ISSUE THREAD

**Issue by riyadm** [juliohm/GeoStats.jl#30]
Hi!

I was thinking it'd be useful to have a set of simple methods for solution postprocessing, e.g.

`mean(solution)`
`var(solution)`
`quantile(solution, p)`

Some of the other possibilities: mean above/below a threshold, probability (frequency) above/below a threshold. 

These are simple, yet provide a nice and quick way of looking at a summary statistic of a solution. Some of these methods may be extended from [Statistics module](https://docs.julialang.org/en/v1/stdlib/Statistics/index.html). 

Would also be great to hear feedback from users on which methods would be useful. Thanks!

**Comment by juliohm** [comment]
That is a great idea. We can start broadening our view of a [SimulationSolution](https://github.com/juliohm/GeoStatsBase.jl/blob/master/src/solutions/simulation_solution.jl) as defined in `GeoStatsBase.jl` to be an *empirical distribution* in which geostatistical realizations are the samples. In this general sense, we could start computing summary statistics like the `mean`, `var`, and `quantile` as suggested.

I think the code should live in `GeoStatsDevTools.jl` because it can be useful to other packages and solvers in the future. I agree we should extend the methods in `Statistics` :+1:

What is still unclear to me is the output format of these functions. What would be useful from a user's perspective? Let's say we take the mean of a solution, what is the format of the output? Should we return a dictionary mapping properties to mean maps? Something like the output of the `digest` function we already have. We could start by returning another `SimulationSolution` object with a single realization containing the mean, and then calling the already implemented `digest` on it as the return value.

If you can sketch an initial implementation of the `mean` function for example in a file called `GeoStatsDevTools.jl/src/solutions/postprocessing.jl` that would be very helpful. Feel free to add your name in the copyright header like in other files ;)

**Comment by juliohm** [comment]
Actually, you could start adding the functions to the existing file `GeoStatsDevTools.jl/src/solutions/simulation_solution.jl`. This is a generic place in the source where we can add functionality for `SimulationSolution` objects.

**Comment by juliohm** [comment]
This is being tracked in https://github.com/juliohm/GeoStatsDevTools.jl/pull/2

**Comment by juliohm** [comment]
Fixed on master, thanks @riyadm.
