### ISSUE TITLE
Unified way of plotting spatial objects

### ISSUE THREAD

**Issue by juliohm** [juliohm/GeoStats.jl#32]
Currently, spatial objects such as spatial data, solutions and statistics have their own plot recipes. This approach works fine, but is hard to maintain. I am opening this issue to discuss possible fixes.

A first proposal would be to define plot recipes for spatial data types only, and write plot recipes for other types in terms of this recipes. That is, to plot a spatial solution, we would find out the corresponding domain onto which it is defined and call the plot recipe for that domain. A solution on a `PointSet` for example could be plotted by converting the solution into a `PointSetData` and plotting it.

@riyadm what is your take on this? Remember we discussed it when you introduced the spatial statistics? Let me know if you have other suggestions.

**Comment by riyadm** [comment]
We could maybe define methods on solutions and statistics converting those to some plottable object (like a separate wrapper?), since the data containing fields are not consistent (`realizations` in `SimulationSolution`, `mean` and `variance` in `EstimationSolution`, and `values` in `SpatialStatistic`). We could then call the recipe depending on domain. Seems like this is very similar to what you suggested. What do you think? Thanks.

**Comment by riyadm** [comment]
We could pass data as a dictionary `Dict{Symbol,Vector}` mapping property name to vector of values. For `EstimationSolution` on `RegularGrid` we would pass `Dict(:mean => mean, :variance => var)`, while `Dict(:var1 => reals1, :var2 => reals2, :var3 =>reals3)` for `SimulationSolution`. Then we can dispatch based on domain, get plot names as `keys(data)`, and seemingly rest of the code stays same. But there is a small inconsistency, since in first case we have `Dict{Symbol,Vector{Real}}`, while in second case its `Dict{Symbol,Vector{Vector}}`. What do you think about this? Thanks!

**Comment by juliohm** [comment]
I am starting to think about an alternative solution that is safer than dispatching all plots to a single type. It really boils down to finding a way to convert a type of the form:

```julia
struct MySpatialObject{D<:AbstractDomain}
  domain::D
  values::Any
end
```

To an intermediate format that makes sense to plot. We could for example define a function: 

```julia
function digest(domain::RegularGrid{T,N}, data::AbstractVector)
  coordinates(domain), reshape(data, size(domain))
end
```

and then use this function inside of plot recipes. So the plot recipes would still vary per type giving us flexibility, but this pre-processing step that is repeated everywhere could live in a single place. I am still trying to think how that would work, or the implications of doing this. We could also spit out the plot recipe itself in this `digest` function to avoid code repetition, but I am not sure.

**Comment by juliohm** [comment]
Check this out. Now we can plot domain objects directly:

```julia
plot(RegularGrid{Float64}(10,10))
plot(RegularGrid{Float64}(10,10,10))
```
![screenshot from 2019-01-19 09-08-21](https://user-images.githubusercontent.com/3345261/51425931-364efa00-1bca-11e9-873c-538086ae2ad8.png)
![screenshot from 2019-01-19 09-08-32](https://user-images.githubusercontent.com/3345261/51425934-3a7b1780-1bca-11e9-976c-e7d6f6ccba3f.png)

and optionally plot data on top of them:

```julia
plot(RegularGrid{Float64}(10,10), 1:100)
```
![screenshot from 2019-01-19 09-09-59](https://user-images.githubusercontent.com/3345261/51425949-78783b80-1bca-11e9-8bea-ba3f7bea2c52.png)

This  means that we can rewrite plot recipes for any spatial object in terms of these new recipes. For example, I have rewritten the solution recipes to just get the underlying domain, and plot the data: https://github.com/juliohm/GeoStatsDevTools.jl/blob/master/src/plotrecipes/solutions/estimation.jl

Now we can write many more recipes for other types such as spatial statistics without repeating the code :slightly_smiling_face: Would you like to give it a try? If you are not too busy, you can create a file `GeoStatsDevTools.jl/src/plotrecipes/statistics.jl` and propose a new plot recipe :+1:

**Comment by juliohm** [comment]
And we can now overlay spatial data types in a domain to check if the problem was setup correctly:

```julia
sdomain = RegularGrid{Float64}(100,100)
sdata = PointSetData(Dict(:z => [1.,0.,1.]), [25. 50. 75.; 25. 75. 50.])

plot(sdomain)
plot!(sdata, ms=4)
```
![screenshot from 2019-01-19 10-55-24](https://user-images.githubusercontent.com/3345261/51427001-21c62e00-1bd9-11e9-908c-880c2f083114.png)

**Comment by juliohm** [comment]
Marking this one as solved :+1:
