### ISSUE TITLE
GPU implementation?

### ISSUE THREAD

**Issue by lboudard** [juliohm/GeoStats.jl#41]
Hi,

I'm new to julia and this package, though I was wondering is there any gpu implementation available yet?
From what I understand implementation would need specific libraries
https://juliacomputing.com/domains/gpus.html

I'm trying to apply ordinary kriging on a problem that has ~ 100.00 observations (and ~200/1000 observations in range) and was looking for best scaling implementation (besides sampling or reducing the observations), if you have any advice on this since you mention it in your documentation?

Thanks!

**Comment by juliohm** [comment]
Hi @lboudard , welcome to the community!

Some solvers exploit GPUs already like ImageQuilting.jl, but there is still a lot of work to to be done in the Kriging-based solvers before adding GPU support.

What you can currently do, and is common practice with Kriging, is to use the option `maxneighbors` and `neighborhood` which trigger the local Kriging version of the solver. In this local version, the linear system being solved is reduced. Unlike global Kriging, the estimates will be approximate, however that is rarely an issue. Theoretically, using neighborhoods is also a means by which you can address the non-stationarity of real data. You force your estimates to be local instead of using all observations that often don't follow a single distribution.

Feel free to reach out in our gitter channel if you have more questions.

**Comment by juliohm** [comment]
Closing the issue, but happy to take more questions on gitter: https://gitter.im/JuliaEarth/GeoStats.jl
