### ISSUE TITLE
GeoStats.jl and single precision

### ISSUE THREAD

**Issue by juliohm** [juliohm/GeoStats.jl#9]
Hi @visr, @masiddique,

First of all I would like to thank you for reporting bugs with Float32, these should all be fixed by now.

Could you please share how single precision is important in your work? I want to make sure GeoStats.jl functions seamlessly with any Real types.

All the estimators, with the exception of Universal Kriging, have a stable numerical solution now. I will try to replace the current LU factorization of the Universal Kriging system by block elimination. In theory, this should improve the accuracy and decrease the differences between estimates on 32 vs. 64 bits data.

**Comment by visr** [comment]
Thanks for the further work on single precision Júlio. I was using this package for DTM interpolation. The values I had were single precision, hence I thought it'd be most efficient if during Kriging everything stays in single precision. Because of all the uncertainties is the DTM, some lower precision in the estimated values are not so much an issue.

I ran the tests after you added the single precision tests (9f87232f2cc2dfa4032d6dce3600e849cd9f6107) and out of 10 or so runs I got one failure:
```
Expression: OKvar_f ≈ OKvar
   Evaluated: 0.00015354156f0 isapprox 0.00015359474451537292
```

You may want to increase the tolerance in this case, because with the randomly generated input data these are bound to happen every now and then. This can be done with `isapprox`, though I'm not sure what appropriate tolerances would be. I believe in my [Gist](https://gist.github.com/visr/1822e7f0d96fd66c46fd944ace4c7f68) this wasn't a problem since I generated the input data as Float32, then converted to Float64, you do it the other way around.

**Comment by juliohm** [comment]
Thank you @visr, you are completely correct. I have fixed the tests to be Float32 -> Float64 instead of the opposite.

Also, thank you for sharing your use case. Please let me know if similar issues appear in the future.
